# Vagrantfile

Vagrant.configure("2") do |config|
    # Configurações comuns para todas as VMs
    config.vm.box = "ubuntu/bionic64" # Você pode trocar pela versão que quiser, como ubuntu/focal64
  
    config.vm.define "master" do |master|
      master.vm.hostname = "master"
      master.vm.network "private_network", ip: "192.168.56.10"
      master.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y docker.io
        systemctl start docker
        systemctl enable docker
        docker swarm init --advertise-addr 192.168.56.10
      SHELL
    end
  
    (1..3).each do |i|
      config.vm.define "node0#{i}" do |node|
        node.vm.hostname = "node0#{i}"
        node.vm.network "private_network", ip: "192.168.56.1#{i}"
        node.vm.provision "shell", inline: <<-SHELL
          apt-get update
          apt-get install -y docker.io
          systemctl start docker
          systemctl enable docker
          # Junta o node ao cluster usando o token que será passado manualmente depois
        SHELL
      end
    end
  end
  